Add basic hint functionality
williamleven/kandidatprojekt2019 pull request #51
Opened 2019-04-05 11:53 UTC by agnesmardh

2019-04-17 08:32 UTC, agnesmardh commented
There are some things left that maybe should be fixed.
 The hint index is in the beginning -1 so the first hint is shown 
 There is a lot going on in Gameboard right now, some things can be own entities/components
 The hint index and help text indes could be in store instead of gameboard

2019-04-19 07:34 UTC, williamleven requested changes
I've commented on some minor problems of which some should be resolved before merge. 

I also think that the functionality of this component should be split up into some smaller components.

2019-04-19 07:34 UTC, williamleven commented on src/components/GameBoard.vue
> +  <div class="image-container" v-bind:class="{ 'image-container-hidden': duckHidden }">
`:class`  binds to `v-bind:class`

Nothing that has to be changed.

2019-04-19 07:34 UTC, williamleven commented on src/components/GameBoard.vue
> +    <p>{{speechBubble}}</p>
Neet with the computed property

2019-04-19 07:34 UTC, williamleven commented on src/components/GameBoard.vue
> +      hintIndex: -1, // So that we not skip the first hint the first time
This seems like an odd workaround

2019-04-19 07:34 UTC, williamleven commented on src/components/GameBoard.vue
> +      this.duckHidden = false
I don't think this should be needed as it should be false to begin with

2019-04-19 07:34 UTC, williamleven commented on src/components/GameBoard.vue
> +      this.hintIndex = -1
See above comment about -1

2019-04-19 07:34 UTC, williamleven commented on src/store.js
> +    hint: 0, // The hint to be shown
Seems to be unused

2019-04-19 07:34 UTC, williamleven commented on src/store.js
> +    incHint (state) {
Seems to be unused

2019-04-19 07:34 UTC, williamleven commented on src/store.js
> +    getHint: state => state.levels[state.level].hints,
should probably be named `getHints`

2019-04-20 08:22 UTC, williamleven approved these changes

2019-04-20 10:56 UTC, merged